name: Build Docker Image

on:
  push:
    branches:
      - master  # adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create env file
      run: |
        touch .env 
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
        echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" > .env
        cat .env

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t mihaiciorobitca/bookstore:latest .

    - name: Push Docker image to Docker Hub
      run: docker push mihaiciorobitca/bookstore:latest
