name: Build Docker Image

on:
  push:
    branches:
      - master  # adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Env 
      env:  
        super_secret: ${{ secrets.MONGO_URI }} 
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t mihaiciorobitca/bookstore:latest .
      
    - name: Push Docker image to Docker Hub
      run: docker push mihaiciorobitca/bookstore:latest
